AWSTemplateFormatVersion: 2010-09-09
Description: |
  First website
Resources:
  CFNInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0a8b4cd432b1c3063
      InstanceType: t2.micro
      KeyName: firstkey
      SecurityGroups:
        - cfn-sec-group
      Tags:
        - Key: name
          Value: First-project
      UserData:
        Fn::Base64:
          !Sub |
            #! /bin/bash
            yum update -y
            yum install httpd
            systemctl start httpd
            systemctl enable httpd
            cd /var/www/html
            wget https://raw.githubusercontent.com/Ozturkmustafa/my-projects/main/Project-101-kittens-carousel-static-website-ec2/static-web/cat0.jpg
            wget https://raw.githubusercontent.com/Ozturkmustafa/my-projects/main/Project-101-kittens-carousel-static-website-ec2/static-web/cat1.jpg
            wget https://raw.githubusercontent.com/Ozturkmustafa/my-projects/main/Project-101-kittens-carousel-static-website-ec2/static-web/cat2.jpg
            wget https://raw.githubusercontent.com/Ozturkmustafa/my-projects/main/Project-101-kittens-carousel-static-website-ec2/static-web/cat3.jpg
